project_id = "cmaeoykagmohbdgwgrsn"

[functions.submit-test-result]
verify_jwt = false

[functions.get-test-result]
verify_jwt = false

[functions.share-page]
verify_jwt = false

[functions.mark-shared]
verify_jwt = false
